### PR TITLE
Task 4

### PR DESCRIPTION
**Pull request by dinasergiyenko**
[Task 4 Description](https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/task4-integration-with-database/task.md)

**General points**
* Task 4.1 is implemented - YES
* Task 4.2 is implemented lambda links are provided and returns data - YES [GetProductList](https://uw929chpm9.execute-api.eu-west-1.amazonaws.com/dev/products) [GetProductById](https://uw929chpm9.execute-api.eu-west-1.amazonaws.com/dev/products/39705279-e3eb-4480-9549-2bef8f2868c7)
* Task 4.3 is implemented lambda links are provided and products is stored in DB - YES [CreateProduct](https://uw929chpm9.execute-api.eu-west-1.amazonaws.com/dev/products)

> curl --location --request POST 'https://uw929chpm9.execute-api.eu-west-1.amazonaws.com/dev/products' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "test",
    "description": "description",
    "price": 123,
    "count": 10
}'

* Your own Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend - YES [Frontend](https://d7m9em9zfm8h7.cloudfront.net/)

**Additional  tasks**
* POST/products lambda functions returns error 400 status code if product data is invalid - NO
* (All languages) - All lambdas return error 500 status code on any error -YES
* (All languages) - All lambdas do console.log for each incoming requests and their arguments - YES
* (All languages) - Transaction based creation of product - YES

### CODE REVIEW

**Comment by Vladqqqqoo** [comment]
sure, please let me know when you are ready

**Comment by buckster12** [comment]
is there anything new? :(

**Comment by Vladqqqqoo** [comment]
Will be done today at the evening

**Comment by dinasergiyenko** [comment]
Hey @Vladqqqqoo @buckster12 could you please take a look, if it is possible? Thanks in advance! :)

**Comment by buckster12** [comment]
Looks good, but I cannot find a sql transaction. Are you sure you have implemented that?

**Comment by Vladqqqqoo** [comment]
Okay. I don't know c# very well, I just have a view about it. 
So I hope you return 500 in case of db losing connection etc. Because I didn't find it. 
Also I didn't get how you do transaction based INSERT operation. Could you please explain? For example in node js we use ``client.query('begin/commit/rollback')``

**Pull request merged**
